[package]
name = "kaspa-wrpc-python"
description = "Kaspa gRPC Python client"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = ["py-sdk"]
py-sdk = [
    "kaspa-rpc-core/py-sdk",
    "kaspa-wrpc-client/py-sdk",
]

[dependencies]
cfg-if.workspace = true
kaspa-consensus-core.workspace = true
kaspa-rpc-core.workspace = true
kaspa-rpc-macros.workspace = true
kaspa-wrpc-client.workspace = true
kaspa-python-macros.workspace = true
pyo3.workspace = true
pyo3-asyncio-0-21.workspace = true
serde_json.workspace = true
thiserror.workspace = true
workflow-core.workspace = true
workflow-rpc.workspace = true